services:
  mongodb:
    image: mongo:latest
    container_name: superheroes_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  backend:
    build: .
    container_name: superheroes_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/${MONGO_DB}?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo_data:
